# Generated by Django 3.1.7 on 2021-03-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='User Name')),
                ('email', models.CharField(max_length=200, verbose_name='Product Price')),
                ('password', models.CharField(max_length=200, verbose_name='Product Units')),
                ('confirm_password', models.CharField(max_length=200, verbose_name='Product Description')),
                ('image', models.ImageField(upload_to='products', verbose_name='Product Image')),
            ],
        ),
    ]
